<?php
error_reporting(0);
session_start();
if($_SESSION['UserId']!="")
{
?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<?php include_once("../title.php");?>		
		<link rel="stylesheet" href="../../assets/css/colorbox.min.css" />
    	<script src="angularjs/new-invoice-script.js"></script>
	</head>

	<body class="no-skin" data-ng-cloak data-ng-app="CategoryModule" data-ng-controller="CategoryController">
		
		<?php include_once("../top.php");?>

		<div class="main-container ace-save-state" id="main-container">
			
			<?php include_once("sidebar.php");?>

			<div class="main-content">
				<?php include_once("../loader.php");?>
				<div class="main-content-inner">
					<div class="page-content" >
					<div  id="no-more-tables">
						<div class="row">
							<div class="col-xs-12 page-header">
		                  	 <div class="col-xs-12 col-sm-12 col-lg-12">
		                  	 	<div class="" >
									<h1>{{pagetitle}}</h1>
									</div>
		<!-- /.page-header --></div>
		                  	 	
			              </div>							
						</div>

							<div class="row" ng-show="FormList">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="space-6"></div>

								<div class="dataTables_wrapper form-inline no-footer" ng-if="pagedItems.length!='0'">
									<div class="row">
										<div class="col-xs-6">
											<div id="dynamic-table_filter" class="dataTables_filter pull-left"><label>Search:</label>
												<input type="text" ng-model="search" class="form-control" placeholder="Search"> &nbsp; Showing {{mypageno*itemsPerPage-itemsPerPage+1}}-{{mypageno*itemsPerPage}} of {{total_count}}
											</div>
										</div>
									</div>
									<table id="dynamic-table" class="table table-bordered table-striped table-condensed cf" >
										<thead class="cf">
											<tr>
												<!-- <th>Sl.No</th> -->
												<th ng-click="sort('InvoiceDate')">Date <span class="glyphicon sort-icon" ng-show="sortKey=='InvoiceDate'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span></th>
												<!-- <th>Sales Order</th> -->
												<th ng-click="sort('InvoiceId')">Dispatch Id
													<span class="glyphicon sort-icon" ng-show="sortKey=='InvoiceId'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
												</th>
												
												<th ng-click="sort('CustomerName')">Party Name
													<span class="glyphicon sort-icon" ng-show="sortKey=='CustomerName'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
												</th>
												<!-- <th  ng-click="sort('Cmobile')" >Customer Mobile
													<span class="glyphicon sort-icon" ng-show="sortKey=='Cmobile'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
												</th> 
												<th  ng-click="sort('Amount')">Amount
													<span class="glyphicon sort-icon" ng-show="sortKey=='Amount'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
												</th>-->
												<th ng-click="sort('UserName')">Bill Generated By
													<span class="glyphicon sort-icon" ng-show="sortKey=='UserName'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
												</th>
												<!-- <th>Reference</th> -->
												<!-- <th>Draft</th> -->
												<!-- <th>Invoice Status</th>
												<th>Package Status</th> -->
												<th>Action</th>
											</tr>
										</thead>										
										<tbody >

											<tr dir-paginate="cat in pagedItems|orderBy:sortKey:reverse|filter:search|itemsPerPage:10 " total-items="{{total_count}}" current-page="mypageno">
												<!-- <td data-title="Sl.No">{{$index+1}}</td> -->
												<td data-title="Date">{{cat.InvoiceDate | date: 'd MMM y'}}</td>
												<!-- <td data-title="Sales Order Id">{{cat.OrderId}}</td> -->
												<td data-title="Bill Id">{{cat.InvoiceId}}</td>
												
												<td data-title="Party Name">{{cat.CustomerName}}</td>
												<!-- <td data-title="Customer Mobile">{{cat.CustomerMobile}}</td> -->
												<!-- <td data-title="Amount">{{cat.InvoiceTotal}}</td> -->
												<td data-title="Bill Generated By">{{cat.UserName}}</td>
												<td data-title="Action">
													<span ng-if="cat.IsSaveDraft=='Yes'" class="label label-warning arrowed-right arrowed-in" >Saved as Draft</span>
													<div  ng-if="cat.IsSaveDraft=='Yes'" class="clearfix">&nbsp;</div>
													<a ng-if="cat.IsSaveDraft=='No'" href="bill-print.php?Id={{cat.PkId}}" target="_blank" class="btn btn-xs btn-info" >Print &nbsp;
														<i class="ace-icon fa fa-print bigger-120"></i>
													</a>

													<!-- <a ng-if="cat.IsSaveDraft=='Yes'" ng-click="GenerateBill(cat.PkId,cat.InvoiceId,cat.InvoiceDate,cat.CustomerId_CustomerMaster,cat.CustomerName,cat.CustomerMobile,cat.CustomerPlace,cat.Reference,cat.IsSaveDraft,cat.SubTotal,cat.DiscType,cat.DiscountVal,cat.DiscountAmount,cat.InvoiceTotal,cat.data2)" target="_blank" class="btn btn-xs btn-danger" >Generate Bill  &nbsp;
														<i class="ace-icon fa fa-arrow-right bigger-120"></i>
													</a> -->	
													<a ng-if="cat.IsSaveDraft=='No'" ng-click="GenerateBill(cat.PkId,cat.InvoiceId,cat.InvoiceDate,cat.CustomerId_CustomerMaster,cat.CustomerName,cat.CustomerMobile,cat.CustomerPlace,cat.Reference,cat.IsSaveDraft,cat.SubTotal,cat.DiscType,cat.DiscountVal,cat.DiscountAmount,cat.InvoiceTotal,cat.CustomerNotes,cat.data2)" target="_blank" class="btn btn-xs btn-inverse" >Edit &nbsp;
														<i class="ace-icon fa fa-edit bigger-120"></i>
													</a>			
												</td>
											</tr>
											
										</tbody>
										<tfoot>
											<tr>
												<td colspan="7">
													<ul class="pagination">
														<li>
													<dir-pagination-controls 
													                max-size="10"
													                direction-links="true"
													                boundary-links="true"
													                 on-page-change="getData(newPageNumber)"
													                  >
													</dir-pagination-controls>
												</li>
												</ul>
												</td>
											</tr>
										</tfoot>
									</table>
								</div>
								</div><!-- /.row -->


								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!--FOrm lising-->


					<div ng-show="FormAdd" >
						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								 <form class="form-horizontal" role="form" id="AddCategoryForm" name="AddCategoryForm" autocomplete="off" enctype="multipart/form-data" novalidate="">
									<input type="hidden" value="{{FormPkId}}">
									<input type="hidden" value="{{IsSaveDraft}}">
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Product Id"> Dispatch Id <span class="error">*</span></label>
										<div class="col-sm-6">
											<input type="text" id="InvoiceId" placeholder="" class="form-control" name="InvoiceId" required  data-ng-model="InvoiceId" disabled="">
												<div class="error" data-ng-show="submitted || AddCategoryForm.InvoiceId.$dirty && AddCategoryForm.InvoiceId.$invalid">
													<small class="error" data-ng-show="AddCategoryForm.InvoiceId.$error.required">Dispatch Id is required.</small>
												</div>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="reason">Dispatch Date <span class="error">*</span></label>

										<div class="col-sm-6">
										<input type="text" class="form-control" name="entrydate"  placeholder="" id="entrydate" ng-model="entrydate" uib-datepicker-popup="dd-MMM-yyyy" is-open="opened.opened1" ng-click="singleopen($event,'opened1')"  datepicker-options="assDate1" required="" ng-change="GetDueDate(entrydate,paymentterms)"> 
											<div class="error" data-ng-show="submitted || AddCategoryForm.entrydate.$dirty && AddCategoryForm.entrydate.$invalid">
												<small class="error" data-ng-show="AddCategoryForm.entrydate.$error.required">Dispatch Date is required.</small>
											</div>
										</div>
									</div>
									<!-- <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Product Id"> Order Number </label>
										
										<div class="col-sm-6">
											<input type="text" id="OrderId" placeholder="" class="form-control" name="OrderId"  data-ng-model="OrderId" >
												<div class="error" data-ng-show="submitted || AddCategoryForm.OrderId.$dirty && AddCategoryForm.OrderId.$invalid">
													<small class="error" data-ng-show="AddCategoryForm.OrderId.$error.required">Order Id is required.</small>
												</div>
										</div>
									</div> -->
									<div class="form-group">
									<label class="col-sm-3 control-label no-padding-right" for="Sub Projects"> Party Name <span class="error">*</span></label>
									<div class="col-sm-6">
									
									<ui-select ng-model="$parent.customername" theme="selectize" title="Choose a person" >
						            <ui-select-match placeholder="Select or search">{{$select.selected.DisplayName}}</ui-select-match>
						            <ui-select-choices  repeat="item in CustomerArray | filter: $select.search">
						              <div><span ng-bind-html="item.DisplayName | highlight: $select.search"></span></div>
						            </ui-select-choices>
						          </ui-select>
									<div class="error" data-ng-show="submitted || AddCategoryForm.customername.$dirty && AddCategoryForm.customername.$invalid">
										<small class="error" data-ng-show="AddCategoryForm.customername.$error.required">Party is required.</small>
									</div>
										<!--<ui-select name="customername" ng-model="$parent.customername" theme="selectize" title="Choose a person"  required ng-change="GetCustomerShip($parent.customername)">
							            	<ui-select-match placeholder="Select or search">{{$select.selected.CompanyName}}</ui-select-match>
							            	<ui-select-choices repeat="item in CustomerArray | filter: $select.search">
								              <div><span ng-bind-html="item.CompanyName | highlight: $select.search"></span></div>
								            </ui-select-choices>
								        </ui-select>
											<div class="error" data-ng-show="submitted || AddCategoryForm.customername.$dirty && AddCategoryForm.customername.$invalid">
												<small class="error" data-ng-show="AddCategoryForm.customername.$error.required">Party Name is required.</small>
											</div>-->
											<!--<a href="#modal-form" data-toggle="modal"><span class="label label-info arrowed-right arrowed-in" ng-click="AddVendor()">New Customer ?</span></a>-->
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Mobile No"> Mobile No </label>
										<div class="col-sm-6">
											<input class="form-control" type="tel" id="customermobileno" name="customermobileno" maxlength="10"  placeholder="" data-ng-model="customermobileno" data-ng-minlength="10" data-ng-maxlength="10" pattern="[6-9]{1}[0-9]{9}" number > 
											<div class="error" data-ng-show="submitted || AddCustomerForm.customermobileno.$dirty && AddCustomerForm.customermobileno.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.customermobileno.$error.required">Mobile-No is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.customermobileno.$error.minlength">Mobile-No is required to be at least 10 digits</small>
												<small class="error" data-ng-show="AddCustomerForm.customermobileno.$error.maxlength">Mobile-No cannot be longer than 10 digits</small>
												<small class="error" data-ng-show="AddCustomerForm.customermobileno.$error.pattern">Mobile No must be number & start from 6-9</small>
											</div>
										</div>
									</div>
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="reason"> Reference No# </label>
										
										<div class="col-sm-6">
										<input type="text" id="referencenum" placeholder="" class="form-control"  name="referencenum"  data-ng-model="referencenum">
											<div class="error" data-ng-show="submitted || AddCategoryForm.referencenum.$dirty && AddCategoryForm.referencenum.$invalid">
												<small class="error" data-ng-show="AddCategoryForm.referencenum.$error.required">Reference Number is required.</small>
											</div>
										</div>
									</div>
									<!-- <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Mobile No">Customer Place </label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="place" name="place"  placeholder="" data-ng-model="place"> 
											<div class="error" data-ng-show="submitted || AddCustomerForm.place.$dirty && AddCustomerForm.place.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.place.$error.required">Place is required.</small>
											</div>
										</div>
									</div> 
									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="reason"> Reference Invoice# </label>
										
										<div class="col-sm-6">
										<input type="text" id="referencenum" placeholder="" class="form-control"  name="referencenum"  data-ng-model="referencenum">
											<div class="error" data-ng-show="submitted || AddCategoryForm.referencenum.$dirty && AddCategoryForm.referencenum.$invalid">
												<small class="error" data-ng-show="AddCategoryForm.referencenum.$error.required">Reference Number is required.</small>
											</div>
										</div>
									</div>-->

									<!-- <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="State">Payment Terms </label>
										<div class="col-sm-6">
											<select  name="paymentterms" class="form-control"  ng-model="paymentterms" ng-change="GetDueDate(entrydate,paymentterms)">
												<option value="">Select State</option>
												<option ng-repeat="term in PaymentTermArr" value="{{term.TermName}}">{{term.TermName}}</option>
											</select>	
											<div class="error" data-ng-show="submitted || AddCategoryForm.paymentterms.$dirty && AddCategoryForm.paymentterms.$invalid">
											<small class="error" data-ng-show="AddCategoryForm.paymentterms.$error.required">Select Payment terms Required</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="reason">Due Date </label>

										<div class="col-sm-6">
										<input type="text" class="form-control" name="duedate"  placeholder="" id="duedate" ng-model="duedate" uib-datepicker-popup="dd-MMM-yyyy" is-open="opened.opened2" ng-click="singleopen($event,'opened2')"  datepicker-options="assDate1" > 
											<div class="error" data-ng-show="submitted || AddCategoryForm.duedate.$dirty && AddCategoryForm.duedate.$invalid">
												<small class="error" data-ng-show="AddCategoryForm.duedate.$error.required">Date is required.</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="State">Delivery Method </label>
										<div class="col-sm-6">
											<input  type="text" name="deliverymethod" class="form-control"  ng-model="deliverymethod">
											<div class="error" data-ng-show="submitted || AddCustomerForm.deliverymethod.$dirty && AddCustomerForm.deliverymethod.$invalid">
											<small class="error" data-ng-show="AddCustomerForm.deliverymethod.$error.required">Delivery Method Required</small>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="State">Sales Person </label>
										<div class="col-sm-6">
											<input  type="text" name="salesperson" class="form-control"  ng-model="salesperson">
											<div class="error" data-ng-show="submitted || AddCustomerForm.salesperson.$dirty && AddCustomerForm.salesperson.$invalid">
											<small class="error" data-ng-show="AddCustomerForm.salesperson.$error.required">Sales Person Required</small>
											</div>
										</div>
									</div>

									<div class="clearfix"></div>
									 <div class="form-group">
									  	<label class="col-sm-3 control-label no-padding-right" for="PinCode">Upload File </label>

										<div class="col-sm-6">
										  <input  type="file" id="IPkId" file-model="docfile" accept="image/*" style="display: none;">
										   <button type="button" id="uploadButton" class="btn btn-sm btn-primary text-small" onclick="document.getElementById('IPkId').click();" >
		                                    <i class="fa fa-paperclip" aria-hidden="true"></i>&nbsp;Choose Files..
		                                  </button> &nbsp;

		                                  {{docfile.name}}
		                              	<small class="error"> {{FileErr}}</small>
		                              	</div>
									</div>  -->
								
									<hr>
									<!-- ng-keydown="GetBar()">  001-Mby1-->
									<div class="">
									<div class="col-sm-6 no-padding-left">
										<input type="text" class="form-control" id="barcodeInput" ng-model="barcodeInput"  placeholder="Scan the bar code here.." 
										ng-model-options="{debounce: 500}" ng-change="GetBar()" autofocus >
									</div>
									<div class="col-sm-6 no-padding-right">
										<ui-select ng-model="$parent.barcode" theme="selectize" title="Choose a person" ng-change="GetSelectBar()">
								            <ui-select-match placeholder="Select or search">{{$select.selected.Size}} MM</ui-select-match>
								            <ui-select-choices group-by="'TotalName'" repeat="item in BarArr | filter: $select.search">
								              <div><span ng-bind-html="item.Size | highlight: $select.search"></span> MM ({{item.UniqueRollNo}}) | {{item.Remarks}}</div>
								            </ui-select-choices>
								          </ui-select>
										<!-- <input type="text" class="form-control" id="typebarcodeInput" ng-model="barcodeInput"  placeholder="Type bar code & Click on Go button.."   uib-typeahead="bar as bar.BarCode for bar in BarArr | filter:$viewValue"> -->
									</div>
									<!-- <div class="col-sm-2">
										<button type="button" class="btn btn-sm btn-success" ng-click="GetSelectBar()">Go</button>
									</div> -->
									</div>
									<div id="no-more-tables">
									<table class="table table-striped table-bordered" >
									<thead>
										<tr>
											<th width="30%">Item Details</th>
											<!-- <th>Order Qty</th>
											<th>Invoice Qty</th> -->
											<!-- <th width="5%">Size & Colour</th> -->
											<!-- <th width="5%">Quantity</th> -->
											<!-- <th width="10%">Sales Price</th>
											<th width="10%">Basic Amt</th>
											<th width="10%">Tax Rate</th>
											<th width="10%">Tax Amt</th>
											<th width="10%">Final Amt</th> -->
											<th width="5%">ACTION</th>
										</tr>
									</thead>
									<tbody>
										<tr ng-repeat="bat in BatchArr">
											<td data-title="Item Details" class="center">
											<div class="form-group">
												<div class="col-sm-12">
												<input type="hidden" value="{{bat.EntryPkId}}">	
												<input type="hidden" value="{{bat.ProductId}}">
												<input type="hidden" value="{{bat.InvPkId}}">
												{{bat.Micron}} {{bat.ProductName}} {{bat.Size}} MM
												<p><strong>Avl Qty:</strong> {{bat.AvlQty}} {{bat.Unit}}</p>
												<p><strong>Roll No:</strong> {{bat.UniqueRollNo}}</p>
												<small class="error" ng-if="bat.DeleteStatus=='1'">Item already dispatched</small>
												</div>
											</div>
											</td>
											<!--<td data-title="Quantity">
												<div class="form-group">
												<div class="col-sm-12">
													<div class="input-group">
													<input type="text" id="quantity{{$index}}" placeholder="" class="form-control" name="quantity{{$index}}" data-ng-model="bat.quantity" required="" ng-change="ChkQty(bat.AvlQty,bat.quantity,$index)" valid-number allow-decimal="true" allow-negative="false" decimal-upto="3">
													<span class="input-group-addon">
														{{bat.Unit}}
													</span>
												</div>
													<div class="error" data-ng-show="submitted || AddCategoryForm.quantity{{$index}}.$dirty &amp;&amp; AddCategoryForm.quantity.$invalid">
														<small class="error" data-ng-show="AddCategoryForm.quantity{{$index}}.$error.required">Quantity is required.</small>
													</div>
													<small class="error">{{bat.QtyError}}</small>
												
												</div>
												</div>
											</td>
											 <td data-title="Rate">
												<div class="form-group">
													<div class="col-sm-12">
													<input type="text" id="price{{$index}}" placeholder="" class="form-control" name="price{{$index}}" data-ng-model="bat.price" maxlength="8" valid-number="" allow-decimal="false" allow-negative="false" required="" readonly="">
														<div class="error" data-ng-show="submitted || AddCategoryForm.price{{$index}}.$dirty &amp;&amp; AddCategoryForm.price.$invalid">
															<small class="error" data-ng-show="AddCategoryForm.price{{$index}}.$error.required">Rate  is required.</small>
														</div>
													</div>
												</div>
											</td>
											<td data-title="Basic Amount" class="center" >
												{{bat.basicamount | number: 2}}
											</td>
											<td data-title="GST Rate">
											<div class="form-group">
												<div class="col-sm-12">
													<select id="taxrate{{$index}}" placeholder="" class="" name="gstrate" data-ng-model="bat.gstrate" convert-to-number  >
														<option value="">Select</option>
														<option ng-repeat="grt in GSTRateArr" value="{{grt}}">{{grt}}</option>
													</select>
													<div class="error" data-ng-show="submitted || AddCategoryForm.gstrate.$dirty && AddCategoryForm.gstrate.$invalid">
														<small class="error" data-ng-show="AddCategoryForm.gstrate.$error.required">Tax Rate is required.</small>
													</div>
												</div>
											</div>
											</td>
											
											 <td data-title="Tax Amount" class="center">
												<div class="col-sm-2">
													<span id="gstamount{{$index}}" ng-model="gstamount" ng-show="span1" ng-bind="GetGstAmt()"></span>{{bat.gstamount ? bat.gstamount : 0 | number:2}}
												</div>
											</td>
											<td data-title="finaltotal" class="center" >
												{{bat.finaltotal | number: 2}}
											</td> -->
											<td data-title="ACTION">
												<!-- <a ng-if="bat.DeleteStatus=='1'" href="" class="orange" ng-click="removeRow($index);GetPurchaseBars()">
													<i class="ace-icon fa fa-trash bigger-130"></i>
												</a> -->
												<span ng-if="bat.DeleteStatus=='0'">
													<a  href="" class="orange" ng-click="removeRow($index);GetPurchaseBars()">
													<i class="ace-icon fa fa-remove bigger-130"></i> Delete
												</a>
											</span>
												<!-- <a class="orange" href="#modal-form" data-toggle="modal" ng-click="EditArr(bat.BatchNo,bat.ManfcBatch,bat.Mfgdate,bat.Expdate,bat.Quantity,$index)">
													<i class="ace-icon fa fa-pencil bigger-130"></i>
												</a> -->
												<span ng-if="bat.DeleteStatus=='1'"><a class="orange" href="" ng-click="DeleteArr(bat.EntryPkId,bat.ProductId,bat.InvPkId,bat.UniqueRollNo)">
													Delete
												</a>
												</span>
											</td>
										</tr>
										<!-- <tr>
											<td colspan="2">&nbsp;</td>
											<td>Total</td>
											<td>
												<span id="sumbasictotal" ng-model="sumbasictotal" ng-show="span1" ng-bind=BasicSum()></span>{{sumbasictotal ? sumbasictotal : 0 | number:2}}
											</td>
											<td>&nbsp;</td>
											<td>
												<span id="gstsum" ng-model="gstsum" ng-show="span1" ng-bind="GSTSum()"></span>{{gstsum ? gstsum : 0 | number:2}}
											</td>
											<td><span id="totalSum" ng-model="sum" ng-show="span1"></span>{{sum ? sum : 0 | number:2}}</td>
											<td>&nbsp;</td>
										</tr>
										 -->
									</tbody>

								</table>

							</div>
								<!-- <div class="form-group" ng-if="FormPkId==undefined">	
								<div class="col-sm-12 col-md-4 col-lg-4">							
								<button type="button" class="btn btn-sm btn-block btn-info" ng-click="AddMore()">Add More</button>
									</div>
								</div> -->

								<!-- <div class="form-group">
									<label class="col-sm-7 control-label no-padding-right" for="Choose ">Sub Total </label>
									<div class="col-sm-3 hidden-xs">&nbsp;</div>
									<div class="col-sm-2">
										<span id="totalSum" ng-model="sum" ng-show="span1" ng-bind="calculateSum()"></span>{{sum ? sum : 0 | number:2}}
									</div>
								</div>

								<div class="form-group" style="display: none">
								<label class="col-sm-7 control-label no-padding-right" for="Choose ">Packing / Forward Charges </label>
								<div class="col-sm-3">&nbsp;</div>
								<div class="col-sm-2">
									<input  type="text" name="additionalcharges" class="form-control"  ng-model="additionalcharges" valid-number="" allow-decimal="true" allow-negative="false" ng-bind="getDiscAmt()">	
									<div class="error" data-ng-show="submitted || AddCategoryForm.additionalcharges.$dirty && AddCategoryForm.additionalcharges.$invalid">
										<small class="error" data-ng-show="AddCategoryForm.additionalcharges.$error.required"> is required.</small>
									</div>

								</div>
							</div>

							<div class="form-group">
								<label class="col-sm-7 control-label no-padding-right" for="Choose ">Discount </label>
								<div class="col-sm-2">
									<div class="control-group">
										<div class="radio">
											<label>
												<input name="disctype" ng-model="disctype" type="radio" class="ace" ng-required="!disctype" value="Percent" >
												<span class="lbl"> %</span>
											</label>
											<label>
												<input name="disctype" ng-model="disctype" type="radio" class="ace" ng-required="!disctype" value="Rupee" >
												<span class="lbl"> Rs.</span>
											</label>
										</div>
									</div>
									<div class="error" data-ng-show="submitted || AddCategoryForm.disctype.$dirty && AddCategoryForm.disctype.$invalid">
										<small class="error" data-ng-show="AddCategoryForm.disctype.$error.required"> is required.</small>
									</div>
								</div>
								<div class="col-sm-1">
									<input  type="text" name="discvalue" class="form-control"  ng-model="discvalue" valid-number="" allow-decimal="true" allow-negative="false" >	
									<div class="error" data-ng-show="submitted || AddCategoryForm.discvalue.$dirty && AddCategoryForm.discvalue.$invalid">
										<small class="error" data-ng-show="AddCategoryForm.discvalue.$error.required"> is required.</small>
									</div>
								</div>
								<div class="col-sm-2">
									{{disctotal || 0 | number: 2}}	
								</div>
							</div>

							<div class="form-group">
								<label class="col-sm-7 control-label no-padding-right" for="Choose ">Return Id (if any)</label>
								<div class="col-sm-2 no-padding-right">
									<input  type="text" name="returnid" class="form-control"  ng-model="returnid" ng-blur="GetReturnAmt(returnid)">
									<small class="error">{{ReturnChk}}</small>
									<div class="error" data-ng-show="submitted || AddCategoryForm.returnid.$dirty && AddCategoryForm.returnid.$invalid">
										<small class="error" data-ng-show="AddCategoryForm.returnid.$error.required">Return Id is required.</small>
									</div>
								</div>
								<div class="col-sm-1 no-padding-left">
									<button ng-click="GetReturnAmt(returnid)" class="btn btn-sm btn-success">Go</button>
								</div>
								<div class="col-sm-2">
									{{returnamt || 0 | number: 2}}	
								</div>
							</div>

							<div class="form-group">
								<label class="col-sm-7 control-label no-padding-right" for="Choose ">Final Total </label>
								<div class="col-sm-3">&nbsp;</div>
								<div class="col-sm-2">
									{{totalamount || 0 | number:2}}

								</div>
							</div> -->

							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="">Customer Notes </label>
								
								<div class="col-sm-6">
									<textarea type="text" id="cnotes" placeholder="" class="form-control" name="cnotes" data-ng-model="cnotes" ></textarea>
										<div class="error" data-ng-show="submitted || AddCategoryForm.cnotes.$dirty && AddCategoryForm.cnotes.$invalid">
											<small class="error" data-ng-show="AddCategoryForm.cnotes.$error.required">Customer Notes is required.</small>
										</div>
								</div>
							</div>
							<!--
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="">Terms & Conditions </label>
								
								<div class="col-sm-6">
									<textarea type="text" id="terms" placeholder="" class="form-control" name="terms" data-ng-model="terms" ></textarea>
										<div class="error" data-ng-show="submitted || AddCategoryForm.terms.$dirty && AddCategoryForm.terms.$invalid">
											<small class="error" data-ng-show="AddCategoryForm.terms.$error.required">Terms & Conditions is required.</small>
										</div>
								</div>
							</div>

							 <div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="">Status <span class="error">*</span></label>
								
								<div class="col-sm-6">
									<select id="status" placeholder="" class="form-control" name="status" data-ng-model="status" required="">
										<option value="">Select</option>
										<option value="1">Draft</option>
										<option value="2">Save & Confirm</option>
									</select>
										<div class="error" data-ng-show="submitted || AddCategoryForm.status.$dirty && AddCategoryForm.status.$invalid">
											<small class="error" data-ng-show="AddCategoryForm.status.$error.required">Status is required.</small>
										</div>
								</div>
							</div> -->



									<!-- <div class="form-group" ng-if="invtrack=='Batch'">
										<div class="col-sm-3">&nbsp;</div>
											<div class="col-sm-6">
											</a>
										</div>
									</div> -->
									


									<!-- <div class="form-group" ng-if="pagetitle=='Edit Product'">
										<label class="col-sm-3 control-label no-padding-right" for="Status"> Status <span class="error">*</span></label>
										<div class="col-sm-9">
											<select  id="status" placeholder="" class="form-control" name="status"  data-ng-model="$parent.status" required="" convert-to-number>
												<option value="">Select</option>
												<option value="1">Active</option>
												<option value="0">Inactive</option>
											</select>
											<div class="error" data-ng-show="submitted || AddCategoryForm.status.$dirty && AddCategoryForm.status.$invalid">
												<small class="error" data-ng-show="AddCategoryForm.status.$error.required">Status  is required.</small>
											</div>
										</div>
									</div> -->
									<!-- <div class="form-group">
										<label class="col-sm-7 control-label no-padding-right" for="Town"> Payment <span class="error">*</span></label>
										<div class="col-sm-4 text-right">
										<table class="table">
											<thead>
												<th>Type</th>
												<th>Amount</th>
											</thead>
												<tbody>
													<tr class="text-left">
														<td>Cash</td>
														<td>
															<input  type="text" name="paycash" class="form-control"  ng-model="paycash" valid-number="" allow-decimal="true" allow-negative="false" ng-bind="TotalPay()">
														</td>
													</tr>
													<tr class="text-left">
														<td>Card</td>
														<td><input  type="text" name="paycard" class="form-control"  ng-model="paycard" valid-number="" allow-decimal="true" allow-negative="false" >	</td>
													</tr>
													<tr class="text-left">
														<td>Online</td>
														<td><input  type="text" name="payothers" class="form-control"  ng-model="payothers" valid-number="" allow-decimal="true" allow-negative="false"></td>
														
													</tr>
													<tr class="text-left"><td>Total</td><td>{{totalpaid || 0 | number:2}}</td></tr>
												</tbody>
										</table>
										</div>
									</div> -->

									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<!-- <button ng-if="pagetitle=='Add New'" class="btn btn-info" type="button" data-ng-click="SaveDraft()">
												<i class="ace-icon fa fa-file bigger-110"></i>
												Save as Draft
											</button> &nbsp; &nbsp;-->
											 
											<button ng-if="pagetitle=='Edit Bill'" class="btn btn-success" type="button" data-ng-click="AddCategoryData()" ng-disabled="FormValid">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Update Order
											</button>
											<button ng-if="pagetitle=='Add New'" class="btn btn-success" type="button" data-ng-click="AddCategoryData()" ng-disabled="FormValid">
												<i class="ace-icon fa fa-check bigger-110"></i>
												Place on Order
											</button>
											&nbsp; &nbsp;
											<button class="btn btn-inverse" type="button" data-ng-click="GotoList()">
												<i class="ace-icon fa fa-close bigger-110"></i>
												Cancel
											</button>
										</div>
									</div>
								</form>
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!--Add lising-->

					<!--modal-->
					<div id="modal-form" class="modal" tabindex="-1" data-backdrop="static" data-keyboard="false">
						<div class="modal-dialog  modal-lg">
							<div class="modal-content">
								<div class="modal-header">
									<div class="col-xs-12">
									<div class="pull-left">
										<h4>Add Customer</h4>
									</div>
									<div class="pull-right">
										<button type="button" class="close" data-dismiss="modal">&times;</button>
									</div>
									</div>
								</div>
								<div class="modal-body">
								<div class="row">
									<form class="form-horizontal" role="form" id="AddCustomerForm" name="AddCustomerForm" autocomplete="off" enctype="multipart/form-data" novalidate="" data-ng-submit="AddCustomerData()">	
								 	<input type="hidden" value="{{FormPkId}}">

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="CustomerId"> CustomerId <span class="error">*</span></label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="CustomerId" name="CustomerId" required placeholder="" data-ng-model="CustomerId" disabled="">
											<div class="error" data-ng-show="submitted || AddCustomerForm.CustomerId.$dirty && AddCustomerForm.CustomerId.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.CustomerId.$error.required">Customer Id is required.</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Choose ">Customer Type <span class="error">*</span></label>
										<div class="col-sm-6">
											<div class="control-group">
												<div class="radio">
													<label>
														<input name="ctype" ng-model="ctype" type="radio" class="ace" ng-required="!ctype" value="Business">
														<span class="lbl"> Business</span>
													</label>
												</div>
												<div class="radio">
													<label>
														<input name="ctype" ng-model="ctype" type="radio" class="ace" ng-required="!ctype" value="Individual">
														<span class="lbl"> Individual</span>
													</label>
												</div>
											</div>
											<div class="error" data-ng-show="submitted || AddCategoryForm.ctype.$dirty && AddCategoryForm.ctype.$invalid">
												<small class="error" data-ng-show="AddCategoryForm.ctype.$error.required"> is required.</small>
											</div>
										</div>
									</div>

									<div class="form-group" style="display: none">
										<label class="col-sm-3 control-label no-padding-right" for="State">Salutation<span class="error">*</span></label>
										<div class="col-sm-6">
											<select type="text" name="salutation" class="form-control"  ng-model="salutation" required="" ng-options="saltt.SalutationName as saltt.SalutationName for saltt in SalutationArr">
												<option value="">Select </option>
												<!-- <option ng-repeat="saltt in SalutationArr" value="{{saltt.SalutationName}}">{{saltt.SalutationName}}</option> -->
											</select>	
											<div class="error" data-ng-show="submitted || AddCustomerForm.salutation.$dirty && AddCustomerForm.salutation.$invalid">
											<small class="error" data-ng-show="AddCustomerForm.salutation.$error.required">Select salutation Required</small>
											</div>
										</div>
									</div>

									<div class="form-group" style="display: none">
										<label class="col-sm-3 control-label no-padding-right" for="Customer name"> Customer Name <span class="error">*</span></label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="newcustomername" name="customername" required placeholder="" data-ng-model="customername" data-ng-minlength="3" pattern="^[a-zA-Z- ]+">
											<div class="error" data-ng-show="submitted || AddCustomerForm.customername.$dirty && AddCustomerForm.customername.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.customername.$error.required">Customer Name is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.customername.$error.minlength">Customer Name is required to be at least 3 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.customername.$error.pattern">Customer Name should alphabets ex:abcd</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Shop name"> Company Name <span class="error">*</span></label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="shopname" name="shopname" placeholder="" data-ng-model="shopname" data-ng-minlength="3" pattern="^[a-zA-Z- ]+">
											<div class="error" data-ng-show="submitted || AddCustomerForm.shopname.$dirty && AddCustomerForm.shopname.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shopname.$error.required">Company Name is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.shopname.$error.minlength">Company Name is required to be at least 3 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.shopname.$error.pattern">Company Name should alphabets ex:abcd</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Email-Id">Email-Id </label>
										<div class="col-sm-6">
											<input type="email" class="form-control" placeholder="" id="emailid" name="emailid" pattern="^[a-zA-Z0-9-\_.]+@[a-zA-Z0-9-\_.]+\.[a-zA-Z0-9.]{2,5}$"  data-ng-model="emailid">						
							                  	<div class="error" data-ng-show="submitted || AddCustomerForm.emailid.$dirty && AddCustomerForm.emailid.$invalid">
													<small class="error" data-ng-show="AddCustomerForm.emailid.$error.required">Email-Id is required.</small>
													<small class="error" data-ng-show="AddCustomerForm.emailid.$error.email && !emailExists">Invalid Email-Id.</small>
												</div>
												<small class="error" data-ng-if="EmailExists">Email-Id already exists</small>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Mobile No"> Mobile No </label>
										<div class="col-sm-6">
											<input class="form-control" type="tel" id="newmobileno" name="mobileno" maxlength="10" placeholder="" data-ng-model="mobileno" data-ng-minlength="10" data-ng-maxlength="10" pattern="[6-9]{1}[0-9]{9}"  number> 

											<div class="error" data-ng-show="submitted || AddCustomerForm.mobileno.$dirty && AddCustomerForm.mobileno.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.mobileno.$error.required">Mobile-No is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.mobileno.$error.minlength">Mobile-No is required to be at least 10 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.mobileno.$error.maxlength">Mobile-No cannot be longer than 10 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.mobileno.$error.pattern">Mobile No must be number & start from 6-9</small>
											</div>
											<small class="error" data-ng-if="MobileExists">Mobile No already exists</small>
										</div>
									</div>


									<!-- <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="shop No"> Office / Shop Mobile No</label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="ofcmobileno" name="ofcmobileno"  placeholder="" data-ng-model="landline" maxlength="14" data-ng-minlength="14" data-ng-maxlength="14" data-ng-pattern="/^[0-9]*$/">
											<div class="error" data-ng-show="AddCustomerForm.ofcmobileno.$dirty && AddCustomerForm.ofcmobileno.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.ofcmobileno.$error.required">Office No. is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.ofcmobileno.$error.minlength">Office No. is required to be at least 14 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.ofcmobileno.$error.maxlength">Office No. is cannot be longer than 14 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.ofcmobileno.$error.pattern">Office should be numeric ex:1234567890</small>
											</div>
										</div>
									</div> -->

									
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Unit"> &nbsp;</label>
										<div class="col-xs-12 col-sm-5">
											<div class="control-group">
												<label class="control-label bolder blue">Billing Address</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Customer name"> Company Name </label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="billingname" name="billingname" placeholder=""  data-ng-model="billingname" data-ng-minlength="3" pattern="^[a-zA-Z- ]+">
											<div class="error" data-ng-show="submitted || AddCustomerForm.billingname.$dirty && AddCustomerForm.billingname.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.billingname.$error.required">Company Name is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.billingname.$error.minlength">Person Name is required to be at least 3 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.billingname.$error.pattern">Person Name should alphabets ex:abcd</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Mobile No">Mobile No </label>
										<div class="col-sm-6">
											<input class="form-control" type="tel" id="mobileno" name="billmobileno" maxlength="10" placeholder="" data-ng-model="billmobileno" data-ng-minlength="10" data-ng-maxlength="10" pattern="[6-9]{1}[0-9]{9}" number> 
											<div class="error" data-ng-show="submitted || AddCustomerForm.billmobileno.$dirty && AddCustomerForm.billmobileno.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.billmobileno.$error.required">Mobile-No is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.billmobileno.$error.minlength">Mobile-No is required to be at least 10 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.billmobileno.$error.maxlength">Mobile-No cannot be longer than 10 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.billmobileno.$error.pattern">Mobile No must be number & start from 6-9</small>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Address">Address </label>
										<div class="col-sm-6">
											<textarea  name="address1" id="address1" class="form-control" ng-model="address1" placeholder="" ></textarea>
												<div class="error" data-ng-show="submitted || AddCustomerForm.address1.$dirty && AddCustomerForm.address1.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.address1.$error.required">Address Required</small>
											</div>
										</div>
									</div>

									<!-- <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Address">Address Lane2</label>
										<div class="col-sm-6">
											<textarea  name="address2" id="address2" class="form-control" ng-model="address2" placeholder=""></textarea>
												<div class="error" data-ng-show="submitted || AddCustomerForm.address2.$dirty && AddCustomerForm.address2.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.address2.$error.required">Address Lane2 Required</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Town">Town</label>
										<div class="col-sm-6">
											<input type="text" name="town" id="town" class="form-control" ng-model="town" placeholder="" >
												<div class="error" data-ng-show="submitted || AddCustomerForm.town.$dirty && AddCustomerForm.town.$invalid">
													<small class="error" data-ng-show="AddCustomerForm.town.$error.required">Town Required</small>
												</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Town">Landmark</label>
										<div class="col-sm-6">
											<textarea  name="landmark" id="landmark" class="form-control" ng-model="landmark" placeholder=""></textarea>
												<div class="error" data-ng-show="submitted || AddCustomerForm.landmark.$dirty && AddCustomerForm.landmark.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.landmark.$error.required">Landmark Required</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="City">City <span class="error">*</span></label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="city" name="city" required placeholder="" data-ng-model="city" data-ng-minlength="3" pattern="^[a-zA-Z- ]+">
											<div class="error" data-ng-show="submitted || AddCustomerForm.city.$dirty && AddCustomerForm.city.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.city.$error.required">City is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.city.$error.minlength">City is required to be at least 3 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.city.$error.pattern">City should alphabets ex:XXX XXX</small>
											</div>
										</div>
									</div>									

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="State">State <span class="error">*</span></label>
										<div class="col-sm-6">
											<input type="text"  name="state" class="form-control"  ng-model="state" required="" uib-typeahead="st as st for st in StateArray | filter:$viewValue" typeahead-editable="false" typeahead-on-select="onCSelect($item, $model, $label)">
											 <select  name="state" class="form-control"  ng-model="state" required=""  ng-change="GetDist(state)" convert-to-number>
												<option value="">Select State</option>
												<option ng-repeat="state in StateArray" value="{{state.PkId}}">{{state.StateName}}</option>
											</select>	 
											<div class="error" data-ng-show="submitted || AddCustomerForm.state.$dirty && AddCustomerForm.state.$invalid">
											<small class="error" data-ng-show="AddCustomerForm.state.$error.required">Select State Required</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="District">District <span class="error">*</span></label>
										<div class="col-sm-6">
											<input type="text"  name="district" class="form-control"  ng-model="district" required="" uib-typeahead="dist as dist for dist in DistrictArray | filter:$viewValue" typeahead-editable="false">
											 <select  name="district" class="form-control"  ng-model="district" required="" convert-to-number>
												 <option value="">Select District</option>
												<option ng-repeat="dist in DistrictArray" value="{{dist.PkId}}">{{dist.DistName}}</option>
											</select>	 
											<div class="error" data-ng-show="submitted || AddCustomerForm.district.$dirty && AddCustomerForm.district.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.district.$error.required">District is required.</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="PinCode">PinCode <span class="error">*</span></label>
										<div class="col-sm-6">
											<input class="form-control" type="tel" id="pincode" name="pincode" maxlength="6" placeholder="" data-ng-model="pincode" data-ng-minlength="6" data-ng-maxlength="6" data-ng-pattern="/^[0-9]*$/"/ required="">
											<div class="error" data-ng-show="submitted || AddCustomerForm.pincode.$dirty && AddCustomerForm.pincode.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.pincode.$error.required">PinCode is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.pincode.$error.minlength">PinCode is required to be at least 6 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.pincode.$error.maxlength">PinCode cannot be longer than 6 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.pincode.$error.pattern">PinCode should be numeric ex:123456</small>
											</div>
										</div>
									</div> -->

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Unit"> &nbsp;</label>
										<div class="col-xs-12 col-sm-5">
											<div class="control-group">
												<label class="control-label bolder blue">Shipping Address</label>
												<div class="checkbox">
													<label>
														
														<input name="form-field-checkbox" type="checkbox" name="sameasbill" ng-model="sameasbill" class="ace" ng-change="ChkdBIll(sameasbill)">&nbsp;
														<span class="lbl"> Same as billing address</span>
													</label>
												</div>

											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Customer name"> Company Name </label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="shippingname" name="shippingname" placeholder=""  data-ng-model="shippingname" data-ng-minlength="3" pattern="^[a-zA-Z- ]+">
											<div class="error" data-ng-show="submitted || AddCustomerForm.shippingname.$dirty && AddCustomerForm.shippingname.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shippingname.$error.required">Company Name is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.shippingname.$error.minlength">Company Name is required to be at least 3 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.shippingname.$error.pattern">Company Name should alphabets ex:abcd</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Mobile No"> Mobile No </label>
										<div class="col-sm-6">
											<input class="form-control" type="tel" id="shipmobileno" name="shipmobileno" maxlength="10" placeholder="" data-ng-model="shipmobileno" data-ng-minlength="10" data-ng-maxlength="10" pattern="[6-9]{1}[0-9]{9}" number> 
											<div class="error" data-ng-show="submitted || AddCustomerForm.shipmobileno.$dirty && AddCustomerForm.shipmobileno.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shipmobileno.$error.required">Mobile-No is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.shipmobileno.$error.minlength">Mobile-No is required to be at least 10 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.shipmobileno.$error.maxlength">Mobile-No cannot be longer than 10 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.shipmobileno.$error.pattern">Mobile No must be number & start from 6-9</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Address">Address </label>
										<div class="col-sm-6">
											<textarea  name="shipaddress1" id="shipaddress1" class="form-control" ng-model="shipaddress1" placeholder="" ></textarea>
												<div class="error" data-ng-show="submitted || AddCustomerForm.shipaddress1.$dirty && AddCustomerForm.shipaddress1.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shipaddress1.$error.required">Address Required</small>
											</div>
										</div>
									</div>

									<!-- <div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Address">Address Lane2</label>
										<div class="col-sm-6">
											<textarea  name="shipaddress2" id="shipaddress2" class="form-control" ng-model="shipaddress2" placeholder=""></textarea>
												<div class="error" data-ng-show="submitted || AddCustomerForm.shipaddress2.$dirty && AddCustomerForm.shipaddress2.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shipaddress2.$error.required">Address Lane2 Required</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Town">Town</label>
										<div class="col-sm-6">
											<input type="text" name="shiptown" id="shiptown" class="form-control" ng-model="shiptown" placeholder="" >
												<div class="error" data-ng-show="submitted || AddCustomerForm.shiptown.$dirty && AddCustomerForm.shiptown.$invalid">
													<small class="error" data-ng-show="AddCustomerForm.shiptown.$error.required">Town Required</small>
												</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="Town">Landmark</label>
										<div class="col-sm-6">
											<textarea  name="shiplandmark" id="shiplandmark" class="form-control" ng-model="shiplandmark" placeholder=""></textarea>
												<div class="error" data-ng-show="submitted || AddCustomerForm.shiplandmark.$dirty && AddCustomerForm.shiplandmark.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shiplandmark.$error.required">Landmark Required</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="City">City <span class="error">*</span></label>
										<div class="col-sm-6">
											<input class="form-control" type="text" id="shipcity" name="shipcity" required placeholder="" data-ng-model="shipcity" data-ng-minlength="3" pattern="^[a-zA-Z- ]+">
											<div class="error" data-ng-show="submitted || AddCustomerForm.shipcity.$dirty && AddCustomerForm.shipcity.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shipcity.$error.required">City is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.shipcity.$error.minlength">City is required to be at least 3 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.shipcity.$error.pattern">City should alphabets ex:XXX XXX</small>
											</div>
										</div>
									</div>									

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="State">State <span class="error">*</span></label>
										<div class="col-sm-6">
											<input type="text"  name="shipstate" class="form-control"  ng-model="shipstate" required=""  uib-typeahead="st as st for st in StateArray | filter:$viewValue" typeahead-editable="false" typeahead-on-select="onCSelect($item, $model, $label)">
											 <select  name="state" class="form-control"  ng-model="state" required=""  ng-change="GetDist(state)" convert-to-number>
												<option value="">Select State</option>
												<option ng-repeat="state in StateArray" value="{{state.PkId}}">{{state.StateName}}</option>
											</select>	 											<div class="error" data-ng-show="submitted || AddCustomerForm.shipstate.$dirty && AddCustomerForm.shipstate.$invalid">
											<small class="error" data-ng-show="AddCustomerForm.shipstate.$error.required">Select State Required</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="District">District <span class="error">*</span></label>
										<div class="col-sm-6">
											<input type="text"  name="shipdistrict" class="form-control"  ng-model="shipdistrict" required="" uib-typeahead="dist as dist for dist in DistrictArray | filter:$viewValue" typeahead-editable="false">
											 <select  name="district" class="form-control"  ng-model="district" required="" convert-to-number>
												 <option value="">Select District</option>
												<option ng-repeat="dist in DistrictArray" value="{{dist.PkId}}">{{dist.DistName}}</option>
											</select>	 
											<div class="error" data-ng-show="submitted || AddCustomerForm.shipdistrict.$dirty && AddCustomerForm.shipdistrict.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shipdistrict.$error.required">District is required.</small>
											</div>
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="PinCode">PinCode <span class="error">*</span></label>
										<div class="col-sm-6">
											<input class="form-control" type="tel" id="shippincode" name="shippincode" maxlength="6" placeholder="" data-ng-model="shippincode" data-ng-minlength="6" data-ng-maxlength="6" data-ng-pattern="/^[0-9]*$/"/ required="">
											<div class="error" data-ng-show="submitted || AddCustomerForm.shippincode.$dirty && AddCustomerForm.shippincode.$invalid">
												<small class="error" data-ng-show="AddCustomerForm.shippincode.$error.required">PinCode is required.</small>
												<small class="error" data-ng-show="AddCustomerForm.shippincode.$error.minlength">PinCode is required to be at least 6 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.shippincode.$error.maxlength">PinCode cannot be longer than 6 characters</small>
												<small class="error" data-ng-show="AddCustomerForm.shippincode.$error.pattern">PinCode should be numeric ex:123456</small>
											</div>
										</div>
									</div> -->

									<div class="form-group" style="display: none;">
										<label class="col-sm-3 control-label no-padding-right" for="State">Payment Terms </label>
										<div class="col-sm-6">
											<select  name="paymentterms" class="form-control"  ng-model="paymentterms" >
												<option value="">Select State</option>
												<option ng-repeat="term in PaymentTermArr" value="{{term.TermName}}">{{term.TermName}}</option>
											</select>	
											<div class="error" data-ng-show="submitted || AddCustomerForm.paymentterms.$dirty && AddCustomerForm.paymentterms.$invalid">
											<small class="error" data-ng-show="AddCustomerForm.paymentterms.$error.required">Select Payment terms Required</small>
											</div>
										</div>
									</div>

									<div class="form-group" style="display: none;">
										<label class="col-sm-3 control-label no-padding-right" for="remarks">
											Remarks
										</label>
										<div class="col-sm-6">
											<textarea  name="remarks" id="remarks" class="form-control" ng-model="remarks" rows="5"></textarea>
											<div class="error" data-ng-show="submitted || AddCustomerForm.remarks.$dirty && AddCustomerForm.remarks.$invalid">
											<small class="error" data-ng-show="AddCustomerForm.remarks.$error.required">Remarks Required</small>
											</div>
										</div>
									</div>

									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="btn btn-info" type="submit" data-ng-disabled="FormValid"  >
												<i class="ace-icon fa fa-check bigger-110"></i>
												Submit
											</button>
											&nbsp; &nbsp;
											<button class="btn btn-inverse" type="button" data-ng-click="GotoList()">
												<i class="ace-icon fa fa-close bigger-110"></i>
												Cancel
											</button>
										</div>
									</div>
									
								</form>
								</div>
								
							</div>
							</div>
						</div>
					</div> <!--modal-->

					<div id="myModal" class="modal" tabindex="-1" data-backdrop="static" data-keyboard="false">
						<div class="modal-dialog  modal-lg">
							<div class="modal-content">
								<div class="modal-header">
									<div class="col-xs-12">
									<div class="pull-left">
										<h4>{{EachBatchArr.length}} Items Found</h4>
									</div>
									<div class="pull-right">
										<button type="button" class="close" data-dismiss="modal">&times;</button>
									</div>
									</div>
								</div>
								<div class="modal-body">
								<div class="row">
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right" for="State">Select Item<span class="error">*</span></label>
										<div class="col-sm-6">
											<ui-select ng-model="$parent.eachproductname" theme="selectize" title="Choose a person">
									            <ui-select-match placeholder="Select or search">{{$select.selected.ProductName}}</ui-select-match>
									            <ui-select-choices  group-by="'Brand'" repeat="item in EachBatchArr | filter: $select.search">
									              <div><span ng-bind-html="item.ProductName | highlight: $select.search"></span></div>
									              <small>Size: <span  ng-bind-html="item.Size | highlight: $select.search"></span></small><br>
									              <small><span  ng-bind-html="item.CategoryName | highlight: $select.search"></span> / <span  ng-bind-html="item.SubCategoryName | highlight: $select.search"></span> / <span  ng-bind-html="item.Level2SCName | highlight: $select.search"></span></small>
									            </ui-select-choices>
									          </ui-select>	
											<div class="error" data-ng-show="submitted || AddCustomerForm.eachproductname.$dirty && AddCustomerForm.eachproductname.$invalid">
											<small class="error" data-ng-show="AddCustomerForm.eachproductname.$error.required">Item is Required</small>
											</div>
										</div>

										<button class="col-sm-2 btn btn-info" type="button" ng-click="SetEachProduct()" data-ng-disabled="FormValid"  >
											<i class="ace-icon fa fa-check bigger-110"></i>
											Go
										</button>
									</div>
								</div>
								
							</div>
							</div>
						</div>
					</div> <!--modal-->

					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->

			<!-- /.main-container ending in footer page -->
		<?php include_once("../footer.php");?>
<script type="text/javascript">
			jQuery(function($) {
		$('[data-rel=popover]').popover({container:'body'});

		if(!ace.vars['touch']) {
					$('.chosen-select').chosen({allow_single_deselect:true}); 
					//resize the chosen on window resize
			
					// $(window)
					// .off('resize.chosen')
					// .on('resize.chosen', function() {
					// 	$('.chosen-select').each(function() {
					// 		 var $this = $(this);
					// 		 $this.next().css({'width': $this.parent().width()});
					// 	})
					// }).trigger('resize.chosen');
					// //resize chosen on sidebar collapse/expand
					// $(document).on('settings.ace.chosen', function(e, event_name, event_val) {
					// 	if(event_name != 'sidebar_collapsed') return;
					// 	$('.chosen-select').each(function() {
					// 		 var $this = $(this);
					// 		 $this.next().css({'width': $this.parent().width()});
					// 	})
					// });
			
				}

	});
</script>
	</body>
</html>
<?php
}
else
{ 
	header('Location: ../logout.php');
  echo "<script language=\"javascript\">window.location=\"../../index.php\";</script>";
}
?>
